name: 'Publish Release'

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read Node version
        id: node_version
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      - name: Set Node version
        uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.node_version.outputs.NVMRC }}'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies and publish
        run: pnpm install --no-frozen-lockfile && pnpm publish:next
        env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} 
            NPM_TOKEN: ${{secrets.NPM_TOKEN}}
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
